#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first README file.
#

set -e; . src/bash/preludes/standard.bash

autogen_ac_start build-aux/autogen.ac
autogen_am_start build-aux/autogen.am

autogen_am_var_append hs_files \
  main/**/*.hs \
  src/**/*.hs \
;

autogen_am_var_append lib_files lib/**/*.psl

autogen_downloads build-aux/downloads

autogen_ac_finish
autogen_am_finish

autoreconf -fivW all

echo success
