#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first README file.
#

set -e; . src/bash/preludes/standard.bash

autogen_ac_start build-aux/autogen.ac
autogen_am_start build-aux/autogen.am

sed '
  s/^\([[:blank:]]*version\): .*$/\1: @PACKAGE_VERSION@/
' <package.yaml >package.yaml.in

autogen_am_var_append_files \
  hs_files \
    main/**/*.hs \
    src/**/*.hs \
;

autogen_am_var_append_files \
  nobase_dist_share_psl_DATA \
    examples-data/**/* \
    examples/**/* \
    lib/**/* \
;

autogen_downloads build-aux/downloads

autogen_ac_finish
autogen_am_finish

autoreconf -fivW all

echo success
