#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first README file.
#

. src/bash/preludes/standard.bash || exit

autogen_ac_start build-aux/autogen.ac
autogen_am_start build-aux/autogen.am

autogen_downloads build-aux/downloads

autogen_ac_finish
autogen_am_finish

autoreconf -fi
