ARG base_image=ubuntu

FROM $base_image AS builder

ENV LC_ALL=C.UTF-8

RUN : \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -qy update \
  && apt-get -qy install curl make \
  && curl -sSL -o install_stack https://get.haskellstack.org/ \
  && sh install_stack \
;

COPY psl-@PACKAGE_VERSION@.tar.gz /x/

RUN : \
  && cd /x \
  && tar xzf psl-@PACKAGE_VERSION@.tar.gz \
  && chown -R root:root psl-@PACKAGE_VERSION@ \
  && cd psl-@PACKAGE_VERSION@ \
  && ./configure \
  && make \
  && make DESTDIR=/x/destdir install \
  && mkdir /x/destdir/root \
  && cd /x/destdir/root \
  && tar xzf /x/psl-@PACKAGE_VERSION@/resource-estimation.tar.gz \
;

FROM $base_image

ENV LC_ALL=C.UTF-8

RUN : \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -q -y update \
  && apt-get -q -y install python python3 python3-pip \
  && python3 -m pip install --user --upgrade pip \
  && python3 -m pip install --user sympy \
;

COPY --from=builder /x/destdir /
WORKDIR /root
