verbatim:
  cabal-version: 2.2

name: symphony
version: 0.1.0.0

default-extensions:
  - ConstraintKinds
  - DataKinds
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RebindableSyntax
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  - UnicodeSyntax
  - ViewPatterns
  - CPP

flags:
  dist:
    default: false
    manual: true


ghc-options:
  - -Wall
  - -Wno-orphans
  - -Wno-partial-type-signatures
  - -j
  - -optP-Wno-nonportable-include-path
  - -g
  - -O2
  - -optc-O3
  - -fspecialise-aggressively
  - -fexpose-all-unfoldings

data-files:
  - programs/**/*

library:
  source-dirs:
    - src/lib
  dependencies:
    - aeson
    - network
    - base
    - binary
    - process
    - bytestring
    - directory
    - filepath
    - cryptonite
    - uvmhs
    - aeson
    - bytestring
    - text
    - vector

tests:
  symphony-test:
    main: Main.hs
    source-dirs:
      - src/test
    dependencies:
      - base
      - text
      - hspec
      - uvmhs
      - symphony

executables:
  symphony:
    main: Main.hs
    source-dirs:
      - src/main
    dependencies:
      - base
      - cryptonite
      - symphony
      - uvmhs
