verbatim:
  cabal-version: 2.2

name: psl
version: 0.1.0.0

default-extensions:
  - ConstraintKinds
  - DataKinds
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RebindableSyntax
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  - UnicodeSyntax
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wno-orphans
  - -Wno-partial-type-signatures
  - -j

data-files:
  - lib/*
  - examples/*
  - tests/*
  - examples-input/**/*

library:
  source-dirs: 
    - src
  dependencies:
    - aeson
    - base
    - bytestring
    - directory
    - filepath
    - random
    - uvmhs
    - aeson
    - bytestring
    - random
    - text

executables:
  psli:
    source-dirs: main
    main: PSLI.hs
    dependencies:
      - base
      - psl
      - uvmhs
