verbatim:
  cabal-version: 2.2

name: symphony
version: 0.1.0.0

default-extensions:
  - ConstraintKinds
  - DataKinds
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RebindableSyntax
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  - UnicodeSyntax
  - ViewPatterns
  - CPP

flags:
  par:
    default: false
    manual: true

ghc-options:
  - -Wall
  - -Wno-orphans
  - -Wno-partial-type-signatures
  - -j
  - -optP-Wno-nonportable-include-path
  - -g
  - -O2
  - -optc-O3
  - -fspecialise-aggressively
  - -fexpose-all-unfoldings

data-dir: data

data-files:
  - ./**/*

library:
  source-dirs:
    - src/lib/common
    - src/lib/seq
  dependencies:
    - aeson
    - network
    - base
    - binary
    - process
    - bytestring
    - directory
    - filepath
    - cryptonite
    - uvmhs
    - aeson
    - bytestring
    - text
    - vector
  when:
    - condition: flag(par)
      source-dirs:
        - src/lib/par
      exposed-modules:
        - Symphony.Dynamic.Par
        - Symphony.Dynamic.Par.Types
        - Symphony.Dynamic.Par.Channel
        - Symphony.Dynamic.Par.Channel.Types
        - Symphony.Dynamic.Par.Dist
        - Symphony.Dynamic.Par.Error
        - Symphony.Dynamic.Par.GMW
        - Symphony.Dynamic.Par.GMW.Types
        - Symphony.Dynamic.Par.Operations
        - Symphony.Dynamic.Par.Prg
        - Symphony.Dynamic.Par.Prg.Types
        - Symphony.Dynamic.Par.Primitives
        - Symphony.Dynamic.Par.ReadType
        - Symphony.Dynamic.Par.Send
        - Symphony.Dynamic.Par.Truncating
      extra-libraries:
        - symphony

tests:
  symphony-test:
    main: Main.hs
    source-dirs:
      - src/test
    dependencies:
      - base
      - text
      - hspec
      - uvmhs
      - symphony

executables:
  symphony:
    main: Main.hs
    source-dirs:
      - src/main
    dependencies:
      - base
      - cryptonite
      - symphony
      - uvmhs
    when:
      - condition: flag(par)
        extra-libraries:
          - symphony
        cpp-options: -DPAR
