#! /bin/bash -

set -euo pipefail

instance_address=ubuntu@52.13.32.244

run_on_instance() {
  ssh $instance_address "bash -c 'set -euo pipefail; '${*@Q}"
}

# Create this beforehand with:
#   git bundle create psl.gitbundle HEAD --tags
scp psl.gitbundle $instance_address:

run_on_instance '(
  sudo apt-get -qy update
  sudo apt-get -qy install bash jq git autoconf automake m4 gcc \
    make python3 python3-pip apt-transport-https ca-certificates \
    curl gnupg-agent software-properties-common parallel screen \
    git python
  python3 -m pip install --user --upgrade pip
  python3 -m pip install --user sympy
  #curl -fsSL https://get.docker.com -o get-docker.sh
  #sudo sh get-docker.sh
  #sudo usermod -aG docker $USER || :
  curl -sSL https://get.haskellstack.org/ | sudo sh
  git clone psl.gitbundle psl
  cd psl
  ./autogen
  ./configure
  make
  sudo make install
)'
