#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first README file.
#

set -e; . src/bash/preludes/gitlab-ci.bash

ubuntu_install_packages \
  autoconf \
  automake \
  gcc \
  git \
  gnupg \
  gnupg1 \
  jq \
  libtool \
  m4 \
  make \
  openssl \
  sshpass \
  texinfo \
  wget \
;

./autogen
./configure
make dist
