#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first README file.
#

set -e; . src/bash/preludes/gitlab-ci.bash

ubuntu_install_images \
  make \
  tar \
;

docker login \
  --username "$CI_REGISTRY_USER" \
  --password-stdin \
  "$CI_REGISTRY" \
  <<<"$CI_REGISTRY_PASSWORD" \
;

image=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/psl
readonly image

tag=$(git log -1 --pretty=%ct)
tag=$(date -ud @$tag +%Y-%m-%d-%H%M%S)
tag=$tag-g$(git rev-parse --short HEAD)

cd "$tmpdir"
tar xzf "$rundir"/*.tar.gz
cd *
./configure
make docker

docker tag psl:latest "$image:$tag"
docker tag psl:latest "$image:latest"

docker push "$image:$tag"
docker push "$image:latest"
