#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first README file.
#

set -e; . src/bash/preludes/gitlab-ci.bash

ubuntu_install_packages \
  make \
  tar \
;

cd "$tmpdir"
tar xzf "$rundir"/*.tar.gz
cd *
./configure
make docker

image=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/psl
readonly image

tags=$(
  docker images \
    --filter 'reference=psl:*' \
    --format '{{.Tag}}' \
  ;
)
readonly tags

for tag in $tags; do
  docker tag psl:latest "$image:$tag"
  docker push "$image:$tag"
done
