#
# For the copyright information for this file, please search up the
# directory tree for the first README file.
#

#
# autogen_print_ac_header
#

if [[ "$(type -t \
autogen_print_ac_header)" != function ]]; then
autogen_print_ac_header() {

  if (($# != 0)); then
    barf 'invalid argument count: %d' $#
  fi

  cat <<"EOF"
dnl
dnl For the copyright information for this file, please search up the
dnl directory tree for the first README file.
dnl

dnl
dnl This file was generated by autogen.
dnl

EOF

}; readonly -f autogen_print_ac_header; fi
